### ISSUE TITLE
when webrequest is done , ESP32 crashes

### ISSUE THREAD

**Issue by Ronald1817** [khoih-prog/WiFiWebServer#18] opened 2022-07-22 11:24 UTC
### Describe the bug

Used example code for WifiServer on ESP32 , Heltec WIFI kit 32.
When visited by browser, the handleRoot function crashes, i see a reboot in the serial monitor on platformio

ESP32 crash when going to visit IP adres in my case 192.168.50.77.
I

### Steps to Reproduce

Visit from webbrowser the ip adres and ESP32 crashes, when closing browser it keeps running.

Steps to reproduce the behavior. Including the [MRE](https://stackoverflow.com/help/minimal-reproducible-example) sketches

### Expected behavior

servicing of html request.

functional servng of HTML code.

### Information

Please ensure to specify the following:

* Arduino IDE version (e.g. 1.8.13) or Platform.io version
* `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0)
* Contextual information (e.g. what you were trying to achieve)
* Simplest possible steps to reproduce
* Anything that might be relevant in your opinion, such as:
  * Operating system (Windows, Ubuntu, etc.) and the output of `uname -a`
  * Network configuration
  
### My setup

Platformio  V.2.5.0
 framework-arduinoespressif32 @ 3.20003.220626 (2.0.3) 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
 - Windows 11 latest

```

Context:
I encountered an endless loop while trying to connect to Local WiFi.

Steps to reproduce:
1. ...
2. ...
3. ...
4. ...
```

### Additional context

[main code ESP32 webserver and mqtt.txt](https://github.com/khoih-prog/WiFiWebServer/files/9167269/main.code.ESP32.webserver.and.mqtt.txt)
[main code ESP32 webserver and mqtt.txt](https://github.com/khoih-prog/WiFiWebServer/files/9167285/main.code.ESP32.webserver.and.mqtt.txt)

Added maim.cpp that i use , 
it's a project for mqtt which works and wanted to add webserver also.

**Comment by khoih-prog** [comment] 2022-07-22 12:57
Hi @Ronald1817 

Try the original [**WebServer** example](https://github.com/khoih-prog/WiFiWebServer/tree/master/examples/WebServer) first on regular or other ESP32_DEV board and **Arduino IDE v1.8.19, ESP32 core v2.0.4**, to see if there is any issue.

If no, **the problem is is your combined code**, not this library. Ask for help in **Arduino / ESP32 / PIO Forum** if the problem persists and you can't solve.

Moving on to PIO, etc. after you're sure your combined code is OK with Arduino IDE, etc.

I'm closing the issue now, and won't reopen until a library's bug is proven by a [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example)

Good Luck,

**Closed by khoih-prog** 2022-07-22 12:57 UTC

**Comment by Ronald1817** [comment] 2022-07-22 14:33
Hi,

 

Thanx for your answer,

 

I am building a clean project but keep getting this:

 



 

 

Member funciton problem  and a constant , 

 

I copied the code and wire.h must be included foro digitalwrite but the errors in above code i can not solve

I am in learning curve fort his.

 

Regards,

Ronald.

 

Van: Khoi Hoang ***@***.***> 
Verzonden: vrijdag 22 juli 2022 14:58
Aan: khoih-prog/WiFiWebServer ***@***.***>
CC: Ronald1817 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [khoih-prog/WiFiWebServer] when webrequest is done , ESP32 crashes (Issue #18)

 

Hi @Ronald1817 <https://github.com/Ronald1817> 

Try the original  <https://github.com/khoih-prog/WiFiWebServer/tree/master/examples/WebServer> WebServer example first on regular or other ESP32_DEV board and Arduino IDE v1.8.19, ESP32 core v2.0.4, to see if there is any issue.

If no, the problem is is your combined code, not this library. Ask for help in Arduino / ESP32 / PIO Forum if the problem persists and you can't solve.

Moving on to PIO, etc. after you're sure your combined code is OK with Arduino IDE, etc.

I'm closing the issue now, and won't reopen until a library's bug is proven by a  <https://stackoverflow.com/help/minimal-reproducible-example> Minimal, Reproducible Example

Good Luck,

**Comment by Ronald1817** [comment] 2022-07-23 07:19
Hi,

thanx for yoyr reply.
i will try the original project.

**Comment by Ronald1817** [comment] 2022-07-23 09:48
Hi,

I want to confirm that when loaded in Arduino IDE 1.8.19 and ESP32 core 2.0.4 it works!
I did not get compiler error that member funtion was not present , it compiled and when i go to the webbrowser i get the graph like the one in the example screenshot.
The conclusion of this is that platformio is not compatible , the examples where written in Arduino IDE , what is your IDE ? is that alway Arduino IDE or do you use VSC + platformio also?

I am glad that it works.
I will now combine my code and see is that works , i will let you know.

**Comment by khoih-prog** [comment] 2022-07-26 16:08
Hi @Ronald1817 

It's good to know you're doing OK now.

> The conclusion of this is that platformio is not compatible

IMO, **PIO is not totally mature yet**, and must require more knowledge and skills to **manually configure / modify** the settings of PIO as well as related libraries, or receiving compiler errors. This currently is the price you have to pay for **better debugging environment,** if necessary or a must.

We're still waiting the days **PIO can compile as easily as Arduino IDE**, without changing anything internally to the libraries' settings.

You can contribute to PIO by posting an issue in PIO Forum and make that day closer.

It'll be beneficial if you'd post the link here after having created the PIO Forum issue.

**Comment by Ronald1817** [comment] 2022-07-26 16:11
Hi,

 

Thanx for your answer.

I will indeed make a contribution to the  PIO forum and maybe it wil be solved.

 

I wil make use of the Arduino IDE fort his project and wil work in reverse

So i will ad my  code tot he project in the Arduino IDE and i tink it wil work then.

 

Regards,

 

Ronald Hofman.

 



 

Van: Khoi Hoang ***@***.***> 
Verzonden: dinsdag 26 juli 2022 18:08
Aan: khoih-prog/WiFiWebServer ***@***.***>
CC: Ronald1817 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [khoih-prog/WiFiWebServer] when webrequest is done , ESP32 crashes (Issue #18)

 

Hi @Ronald1817 <https://github.com/Ronald1817> 

It's good to know you're doing OK now.

The conclusion of this is that platformio is not compatible

IMO, PIO is not totally mature yet, and must require more knowledge and skills to manually configure / modify the settings of PIO as well as related libraries, or receiving compiler errors. This currently is the price you have to pay for better debugging environment, if necessary or a must.

We're still waiting the days PIO can compile as easily as Arduino IDE, without changing anything internally to the libraries' settings.

You can contribute to PIO by posting an issue in PIO Forum and make that day closer.

It'll be beneficial if you'd post the link here after having created the PIO Forum issue.

**Comment by Ronald1817** [comment] 2022-07-27 15:30
Hi,

 

First i want to inform that the ESP32 webserver runs for days now.

 

I created a topic on platfformio with the following link.

 

https://community.platformio.org/t/webserver-esp32-fails-and-in-arduino-ide-it-works/28969

 

I hope that someone wil try it.

 

For now i stick with the Arduino IDE because it;s clear that there are compatibility  issue’s.

 

It’s a pitty that Arduino IDe has little debug capabilities.

 

 

 

Met vriendelijke groet,

 

Ronald Hofman.

 



 

Van: Khoi Hoang ***@***.***> 
Verzonden: dinsdag 26 juli 2022 18:08
Aan: khoih-prog/WiFiWebServer ***@***.***>
CC: Ronald1817 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [khoih-prog/WiFiWebServer] when webrequest is done , ESP32 crashes (Issue #18)

 

Hi @Ronald1817 <https://github.com/Ronald1817> 

It's good to know you're doing OK now.

The conclusion of this is that platformio is not compatible

IMO, PIO is not totally mature yet, and must require more knowledge and skills to manually configure / modify the settings of PIO as well as related libraries, or receiving compiler errors. This currently is the price you have to pay for better debugging environment, if necessary or a must.

We're still waiting the days PIO can compile as easily as Arduino IDE, without changing anything internally to the libraries' settings.

You can contribute to PIO by posting an issue in PIO Forum and make that day closer.

It'll be beneficial if you'd post the link here after having created the PIO Forum issue.

**Comment by khoih-prog** [comment] 2022-07-27 16:55
You can have more debugging messages in Arduino IDE, when necessary, by modifying to use max `_WIFI_LOGLEVEL_` in `defines.h`, such as

```
#define _WIFI_LOGLEVEL_             4
```

from these lines

https://github.com/khoih-prog/WiFiWebServer/blob/d7048a2814c9a07139c5ed3f7edd8c722e052299/examples/WebServer/defines.h#L17-L19
