### ISSUE TITLE
HTTPS / TLS / Secure Post or someway to encrypt traffic

### ISSUE THREAD

**Issue by modemmike** [khoih-prog/WiFiWebServer#19] opened 2022-08-05 03:11 UTC
Let me start by saying I already know HTTPS is not possible on these SAMD devices but can anyone recommend some way of encrypting the communications to prevent man in the middle? I'm posting data to the server which I'd like to not be in plain text. Someone could in theory watch the traffic with WireShark and figure out the API commands being sent to my SAMD devices (matrix portal). Maybe AES? I'm very new to this type of development so I'm struggling to figure out something lightweight enough to run on these.

**Comment by khoih-prog** [comment] 2022-08-11 03:04
Hi @modemmike 

> I already know HTTPS is not possible on these SAMD devices

SAMD using [**WiFiNINA_Generic**](https://github.com/khoih-prog/WiFiNINA_Generic), [**WiFiNINA**](https://github.com/arduino-libraries/WiFiNINA) or [**EthernetWebServer_SSL**](https://github.com/khoih-prog/EthernetWebServer_SSL) library can use SSL/TLS as **client**.

It's not advisable to use SAMD as **SSL/TLS server** because of processing-power limitation.

I'm closing the issue now as this is not a bug of this library and not a good enhancement for this **WiFiWebServer** library.

I suggest you post on Arduino Forum to ask for help or advice for your project.

Good Luck,

**Closed by khoih-prog** 2022-08-11 03:04 UTC
